before_script:
  - apk update
  - apk upgrade
  - apk add bash
  - apk add openssh-client

update-server:
  script:
    - mkdir .ssh
    - chmod 700 .ssh
    - echo "$PRIV_KEY" | tr -t '\r' > .ssh/id_rsa
    - chmod 600 .ssh/id_rsa
    - bash ./thing.bash