image: alpine:latest
before_script:
  - apk update
  - apk upgrade
  - apk add bash
  - apk add openssh-client
  - apk add rsync
  - apk add npm
  - npm install webpack webpack-cli

update-server:
  stage: deploy
  only:
    - master
  script:
    - mkdir .ssh
    - chmod 700 .ssh
    - echo "$PRIV_KEY" | tr -d '\r' > .ssh/id_rsa
    - chmod 600 .ssh/id_rsa
    - ls
    - cd /frontend/Tasklists
    - npm run build
    - rsync -a --dry-run /frontend/Tasklists/dist ${SERVER_USER}@${SERVER_IP}:/var/www/frontend/Tasklists/dist
    - bash ./thing.bash