before_script:
  - apt update
  - apt upgrade
  - apt add bash
  - apt add openssh-client

update-server:
  stage: deploy
  only:
    - master
  script:
    - mkdir .ssh
    - chmod 700 .ssh
    - echo "$PRIV_KEY" | tr -d '\r' > .ssh/id_rsa
    - chmod 600 .ssh/id_rsa
    - bash ./thing.bash