before_script:
  - apt-get update
  - apt-get upgrade
  - apt-get -y install bash
  - apt-get -y install openssh-client
  - apt-get -y install rsync
  - apt-get -y install npm

update-server:
  stage: deploy
  only:
    - master
  except:
    changes:
      - frontend/src/**/*
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  script:
    - mkdir .ssh
    - chmod 700 .ssh
    - echo "$PRIV_KEY" | tr -d '\r' > .ssh/id_rsa
    - chmod 600 .ssh/id_rsa
    - bash ./thing.bash

build-js-update-server:
  stage: build
  only:
    refs:
      - master
    changes:
      - frontend/src/**/*
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  script:
    - mkdir .ssh
    - chmod 700 .ssh
    - echo "$PRIV_KEY" | tr -d '\r' > .ssh/id_rsa
    - chmod 600 .ssh/id_rsa
    - cd frontend/
    - npm --version
    - npm install --verbose
    - npm install -g webpack
    - npm install -g webpack-cli
    - npx webpack --mode="production"
    - cd ../
    - bash ./thing.bash
    - rsync -a -e "ssh -i $KEY_PATH" frontend/dist/ $SERVER_USER@$SERVER_IP:/var/www/frontend/dist