image: alpine:latest
before_script:
  - apk update
  - apk upgrade
  - apk add bash
  - apk add openssh-client
  - apk add rsync
  - apk add npm

update-server:
  stage: deploy
  only:
    - master
  script:
    - mkdir .ssh
    - chmod 700 .ssh
    - echo "$PRIV_KEY" | tr -d '\r' > .ssh/id_rsa
    - chmod 600 .ssh/id_rsa
    - cd frontend/Tasklists
    - npm install
    - npm install -g webpack
    - npm install -g webpack-cli
    - npx webpack --mode="production"
    - echo $KEY_PATH
    - echo /build/JacobPuff/dev-server/.ssh/
    - rsync -a --dry-run -e "ssh -i $KEY_PATH" dist $SERVER_USER@$SERVER_IP:/var/www/frontend/Tasklists/dist
    - bash ./thing.bash